- hosts: 127.0.0.1
  connection: local
  tags: build
  tasks:
      - name: Remove old resources
        file:
            path: "{{ item }}"
            state: absent
        with_items:
            - resources/css
            - resources/js

      - name: Install all deps
        command: npm i

      - name: Build latest version
        command: npm run build

- hosts: server
  become: true
  tags: deploy
  tasks:
      - name: Pull latest
        command: chdir=/home/centos/personal-website-vue git pull
        register: git_output
        changed_when: git_output.stdout.find( 'Already up-to-date.' ) == -1

      - name: Ensure we have the latest version of node moduels
        command: chdir=/home/centos/personal-website-vue npm ci --only=prod

      - name: Reload the pm2 god daemon
        command: pm2 reload site

      - name: Check if everything is running
        shell: pm2 status site
        register: pm2_output
        until: pm2_output.stdout.find( 'online' ) != -1
        delay: 2
        retries: 5